"""CLI demo: end-to-end IB generation on the synthetic XYZ-001 corpus.

This runs the full pipeline:
  1. LocalFileConnector ingests samples/synthetic_compound/sources/
  2. The parser registry chunks every document
  3. ReportGenerator runs plan -> fill -> critique against the ICH E6 IB
     template using a "smart stub" LLM client (no Vertex access required)
  4. The result is dumped to samples/synthetic_compound/output/ib_run.json

To run with the real Vertex AI Claude (once you have ADC + project access),
pass `--vertex-project` and `--vertex-region`; the script swaps the stub for
VertexLlmClient automatically.

Usage:
    # With the stub (no GCP needed):
    python samples/run_synthetic_ib.py

    # With Vertex AI Claude (after `gcloud auth application-default login`):
    python samples/run_synthetic_ib.py --vertex-project my-gsk-project --vertex-region us-east5

Outputs: samples/synthetic_compound/output/ib_run.json
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from services.api_integration import (  # noqa: E402
    ApiCallGate,
    ApiConnectorRegistry,
    MockChemblConnector,
)
from services.audit import (  # noqa: E402
    AnchorPeriod,
    Anchorer,
    AuditQuery,
    AuditSink,
    LocalRsaKeypair,
    LocalRsaSigner,
    SqliteAuditStore,
    verify_chain,
)
from services.data_integration import (  # noqa: E402
    NamedQueryRegistry,
    SqlSafetyGate,
    SqliteQueryExecutor,
)
from services.document_renderer import (  # noqa: E402
    DryRunRenderer,
    spec_from_report,
)
from services.generation_orchestrator.orchestrator import ReportGenerator  # noqa: E402
from services.ingestion_service.connectors import (  # noqa: E402
    ConnectorContext,
    LocalFileConnector,
)
from services.parsing_service.registry import default_registry  # noqa: E402
from shared.llm import (  # noqa: E402
    LlmClient,
    LlmRequest,
    LlmResponse,
    StubLlmClient,
)
from shared.schemas import ReportTemplate  # noqa: E402


QUERIES_DIR = Path(__file__).resolve().parent / "synthetic_compound" / "queries"
EDC_SQLITE = Path(__file__).resolve().parent / "synthetic_compound" / "edc.sqlite"


SOURCES = REPO_ROOT / "samples" / "synthetic_compound" / "sources"
OUTPUT_DIR = REPO_ROOT / "samples" / "synthetic_compound" / "output"
IB_TEMPLATE_PATH = REPO_ROOT / "templates" / "library" / "ich_e6_ib.json"
METADATA_PATH = REPO_ROOT / "samples" / "synthetic_compound" / "metadata.json"


_CITATION_RE = re.compile(r"\[citation_id=([0-9a-f-]+)\]")


def _build_smart_stub() -> StubLlmClient:
    """Same shape as the test stub: emits structurally valid responses by
    parroting citation_ids back."""
    stub = StubLlmClient(strict=True)

    stub.register_handler(
        lambda r: r.response_schema_name == "PlanOutput",
        lambda r: stub.make_response(
            parsed_json={
                "overall_summary": "Stub plan for the synthetic XYZ-001 IB.",
                "section_plans": [],
            }
        ),
    )

    def fill_gen(r: LlmRequest) -> LlmResponse:
        user_msg = r.messages[-1].content
        ids = _CITATION_RE.findall(user_msg)
        m_lo = re.search(r"Target length:\s*(\d+)-(\d+)\s*words", user_msg)
        lo = int(m_lo.group(1)) if m_lo else 200
        hi = int(m_lo.group(2)) if m_lo else 800
        target = (lo + hi) // 2

        section_match = re.search(r"# Section: ([^\n]+)\n", user_msg)
        title = section_match.group(1).strip() if section_match else "Section"
        body = (
            f"This section ({title}) was generated by the stub LLM client for the "
            "synthetic XYZ-001 corpus. Replace the stub with VertexLlmClient + "
            "Application Default Credentials to produce real Claude output. "
        ) * max(1, target // 30)
        words = body.split()
        if len(words) > hi:
            body = " ".join(words[:hi])
        claims = []
        if ids:
            claims.append({"text": "Stub claim with real citation.", "citation_ids": [ids[0]]})
        return stub.make_response(
            parsed_json={"paragraphs": [{"text": body, "claims": claims}]}
        )

    stub.register_handler(lambda r: r.response_schema_name == "FillOutput", fill_gen)
    stub.register_handler(
        lambda r: r.response_schema_name == "CritiqueOutput",
        lambda r: stub.make_response(parsed_json={"verdict": "pass", "issues": []}),
    )
    return stub


def _build_vertex_client(project: str, region: str, base_url: str | None) -> LlmClient:
    from shared.llm import VertexConfig, VertexLlmClient

    return VertexLlmClient(
        VertexConfig(project_id=project, region=region, base_url=base_url)
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--vertex-project", help="GCP project for Vertex AI Claude")
    parser.add_argument("--vertex-region", default="us-east5")
    parser.add_argument(
        "--vertex-base-url",
        help="Kong / proxy base URL if Vertex AI is fronted by a gateway",
    )
    parser.add_argument(
        "--render-gdoc",
        action="store_true",
        help=(
            "Render the generated IB to a Google Doc in your Drive. Requires "
            "`gcloud auth application-default login` first. Defaults to a "
            "dry-run JSON render."
        ),
    )
    parser.add_argument(
        "--drive-folder-id",
        help="Optional Drive folder ID to place the rendered Doc into",
    )
    parser.add_argument(
        "--anchor",
        action="store_true",
        help=(
            "After generation, compute a signed Merkle root over the audit "
            "chain (Validated-mode mechanic). Uses a local RSA key for the "
            "PoC; production swaps in KmsRootSigner against a Cloud KMS HSM key."
        ),
    )
    args = parser.parse_args()

    metadata = json.loads(METADATA_PATH.read_text(encoding="utf-8"))
    template = ReportTemplate.model_validate(
        json.loads(IB_TEMPLATE_PATH.read_text(encoding="utf-8"))
    )

    print(f"Ingesting from: {SOURCES}")
    connector = LocalFileConnector()
    ctx = ConnectorContext(tenant_id="gsk", team_id="ib-pilot", run_id="demo")
    registry = default_registry()
    docs = []
    chunks_by_doc: dict[str, list] = {}
    for doc, raw in connector.ingest(str(SOURCES), ctx):
        docs.append(doc)
        chunks_by_doc[doc.doc_id] = registry.parse(doc, raw)
    total_chunks = sum(len(c) for c in chunks_by_doc.values())
    print(f"  -> {len(docs)} documents, {total_chunks} chunks")

    if args.vertex_project:
        print(f"Using VertexLlmClient (project={args.vertex_project}, region={args.vertex_region})")
        client: LlmClient = _build_vertex_client(
            args.vertex_project, args.vertex_region, args.vertex_base_url
        )
    else:
        print("Using StubLlmClient (no Vertex access required)")
        client = _build_smart_stub()

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    audit_db_path = OUTPUT_DIR / "audit.sqlite"
    audit_store = SqliteAuditStore(audit_db_path)
    audit_sink = AuditSink(audit_store)
    print(f"Audit ledger:     {audit_db_path}")

    # Wire the named-query registry + SQL safety gate against the local EDC SQLite.
    # If the EDC database hasn't been seeded yet, generate it on demand.
    if not EDC_SQLITE.exists():
        from samples.synthetic_compound.seed_db import seed as _seed_edc
        _seed_edc()
    query_registry = NamedQueryRegistry.from_directory(QUERIES_DIR)
    query_executor = SqliteQueryExecutor(
        EDC_SQLITE, source="edc_warehouse", read_only=True
    )
    safety_gate = SqlSafetyGate(executor=query_executor, registry=query_registry)
    print(f"Named queries:    {len(query_registry)} loaded from {QUERIES_DIR.name}/")

    # API connector layer: register the mock ChEMBL connector so the IB
    # Introduction section's api_call binding (target_biology) can resolve.
    api_registry = ApiConnectorRegistry()
    api_registry.register(MockChemblConnector())
    api_gate = ApiCallGate(api_registry)
    print(f"API connectors:   {len(api_registry)} registered ({', '.join(api_registry.ids())})")

    generator = ReportGenerator(
        fill_client=client,
        audit_sink=audit_sink,
        safety_gate=safety_gate,
        api_gate=api_gate,
        max_retries_per_section=1,
    )
    inputs = {
        "product_name": metadata["compound"]["research_code"],
        "compound_id": metadata["compound"]["research_code"],
        # Target name routed to the ChEMBL connector via the
        # `target_biology` api_call binding in Section 1.
        "target_name": "Kinase Z",
        "sponsor_name": metadata["compound"]["sponsor"],
        "ib_edition": metadata["compound"]["ib_edition"],
        "release_date": metadata["compound"]["ib_release_date"],
    }
    print("Generating IB...")
    project_id = f"ib-pilot/{metadata['compound']['research_code']}"
    result = generator.generate(
        template=template,
        documents=docs,
        chunks_by_doc=chunks_by_doc,
        free_text_inputs=inputs,
        compliance_mode="rd",
        project_id=project_id,
        tenant_id="gsk",
        actor_id=metadata["compound"]["sponsor"],
    )

    n_sections = len(template.all_sections())
    n_paragraphs = sum(
        len(s.paragraphs)
        for s in _walk_generated(result.instance.sections)
    )
    print(
        f"  -> {n_sections} sections processed, {n_paragraphs} paragraphs, "
        f"{len(result.citations)} citations, {len(result.audit_events)} audit events"
    )

    # Audit chain integrity check (per-project)
    project_chain = list(audit_store.query(AuditQuery(project_id=project_id)))
    n_verified = verify_chain(project_chain)
    print(f"Audit chain verified: {n_verified} events ({project_id})")

    # Per-action counts (a quick QMS-style summary)
    from collections import Counter
    counts = Counter(e.action.value for e in project_chain)
    for action, n in sorted(counts.items()):
        print(f"  {action:<35s} {n}")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = OUTPUT_DIR / "ib_run.json"
    out_path.write_text(
        json.dumps(
            {
                "instance": result.instance.model_dump(mode="json"),
                "citations": [c.model_dump(mode="json") for c in result.citations],
                "audit_events": [e.model_dump(mode="json") for e in result.audit_events],
                "plan_summary": result.plan.overall_summary if result.plan else None,
            },
            indent=2,
            default=str,
        ),
        encoding="utf-8",
    )
    print(f"Wrote run JSON:    {out_path}")

    # Optional Validated-mode anchoring: sign a Merkle root over the chain.
    if args.anchor:
        if not project_chain:
            print("Skipping --anchor: no events on the chain.")
        else:
            keypair = LocalRsaKeypair.generate(signer_id="local:demo-rsa-3072")
            signer = LocalRsaSigner(keypair)
            period = AnchorPeriod(
                project_id=project_id,
                period_start=project_chain[0].timestamp_utc,
                period_end=project_chain[-1].timestamp_utc,
            )
            anchor = Anchorer(store=audit_store, signer=signer).anchor(
                period, notes=["demo run; local RSA key (not HSM-backed)"]
            )
            anchor_path = OUTPUT_DIR / "anchor.json"
            anchor_path.write_text(
                anchor.model_dump_json(indent=2), encoding="utf-8"
            )
            # Also save the public key for any future verifier.
            (OUTPUT_DIR / "anchor.pub.pem").write_bytes(keypair.public_pem)
            print(f"Anchor written:   {anchor_path}")
            print(
                f"  merkle_root={anchor.merkle_root_hex[:24]}... "
                f"signer={anchor.signer_id} events={anchor.event_count}"
            )

    spec = spec_from_report(result.instance, result.citations)
    if args.render_gdoc:
        from services.document_renderer import GoogleDocsConfig, GoogleDocsRenderer

        if GoogleDocsRenderer is None:
            print("ERROR: GoogleDocsRenderer is unavailable (google-api-python-client missing)")
            return 1
        cfg = GoogleDocsConfig(target_drive_folder_id=args.drive_folder_id)
        renderer = GoogleDocsRenderer(config=cfg)
        artifact = renderer.render(spec)
        print(f"Rendered Google Doc: {artifact.document_url}")
        print(f"  ({artifact.n_operations} Docs API operations)")
    else:
        render_path = OUTPUT_DIR / "ib_render.json"
        artifact = DryRunRenderer(render_path).render(spec)
        print(f"Dry-run render:   {artifact.json_path}")
        print(f"  ({artifact.n_operations} operations; pass --render-gdoc to create a real Google Doc)")

    return 0


def _walk_generated(sections):
    for s in sections:
        yield s
        yield from _walk_generated(s.children)


if __name__ == "__main__":
    raise SystemExit(main())
